### ISSUE TITLE
DataLogger pause function does mess up data triggering

### ISSUE THREAD

**Issue by BenediktBurger** [BenediktBurger/pyleco-extras#13]
Bug report:

Problem: Der Pause button war nicht angeclickt/blau hinterlegt und die Daten kamen bruchstückweise rein, ein click auf den Pause button (nun blau hinterlegt) löst das Problem und alles funktioniert wie es soll. Wird der Pause button nun wieder geclickt, sind die Daten wieder bruchstückig im Datalogger. Stellt man die Ansicht auf Dots um, sind plötzlich alle? Datenpunkte vorhanden, auch welche die vorher im Linien Modus einfach nicht angezeigt wurden, egal ob pausiert oder nicht.

Wie tritt der Fehler auf: Datalogger läuft problemlos --> Pause Knopf drücken und anschließend den Start Knopf --> Daten im Linienmodus bruchstückhaft, aber bei dots sind alle Daten da

Außerdem ist mir noch aufgefallen, dass wiederholtes pausieren und starten das Problem verschlimmert.

**Comment by BenediktBurger** [comment]
Avenue of research: Probably a timer is still alive in the background, happily triggering data points.
Each time pausing and unpausing, a new timer is added, accumulating many timers, making the problem worse.

**Comment by NoahDornhecker** [comment]
If you pause and then unpause the runnig datalogger and start a new measurement, the problem does not occur.
